# Generated by Django 4.0.6 on 2022-10-19 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tag_alter_event_options_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 8, 32, 55, 144899, tzinfo=utc)),
        ),
    ]
