# Generated by Django 4.0.6 on 2022-10-19 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=events.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 11, 7, 3, 374815, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
