# Generated by Django 4.0.6 on 2022-10-24 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_image_alter_event_created_date_delete_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 9, 11, 47, 552316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/event'),
        ),
    ]
