# Generated by Django 4.0.6 on 2022-10-24 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_image_price_alter_event_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 10, 21, 10, 17352, tzinfo=utc)),
        ),
    ]
